### ISSUE TITLE
ImportError: No module named githu

### ISSUE THREAD

**Issue by zappee** [aqeelanwar/StatTheGit#4]
```
python fetch_stats.py --username ... --GitToken ... --RepoNames ...
Traceback (most recent call last):
  File "fetch_stats.py", line 5, in <module>
    from github import Github
ImportError: No module named github

```

```
pip install pygithub 
Requirement already satisfied: pygithub in /home/soma/.local/lib/python3.8/site-packages (1.51)
Requirement already satisfied: requests>=2.14.0 in /home/soma/.local/lib/python3.8/site-packages (from pygithub) (2.23.0)
Requirement already satisfied: pyjwt in /usr/lib/python3/dist-packages (from pygithub) (1.7.1)
Requirement already satisfied: deprecated in /home/soma/.local/lib/python3.8/site-packages (from pygithub) (1.2.10)
Requirement already satisfied: idna<3,>=2.5 in /home/soma/.local/lib/python3.8/site-packages (from requests>=2.14.0->pygithub) (2.9)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/soma/.local/lib/python3.8/site-packages (from requests>=2.14.0->pygithub) (1.25.9)
Requirement already satisfied: certifi>=2017.4.17 in /home/soma/.local/lib/python3.8/site-packages (from requests>=2.14.0->pygithub) (2020.4.5.1)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/lib/python3/dist-packages (from requests>=2.14.0->pygithub) (3.0.4)
Requirement already satisfied: wrapt<2,>=1.10 in /home/soma/.local/lib/python3.8/site-packages (from deprecated->pygithub) (1.12.1)

```

another try:

```
$ python3 fetch_stats.py ...
   _____ _        _ _______ _           _____ _ _
  / ____| |      | |__   __| |         / ____(_) |
 | (___ | |_ __ _| |_ | |  | |__   ___| |  __ _| |_
  \___ \| __/ _` | __|| |  | '_ \ / _ \ | |_ | | __|
  ____) | || (_| | |_ | |  | | | |  __/ |__| | | |_
 |_____/ \__\__,_|\__||_|  |_| |_|\___|\_____|_|\__|
  0%|                                                                                                                                                                                               | 0/9 [00:00<?, ?it/s]Processing:  jceks-tool
  0%|                                                                                                                                                                                               | 0/9 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "fetch_stats.py", line 58, in <module>
    repo = g.get_repo(repo_str)
  File "/home/xxx/.local/lib/python3.8/site-packages/github/MainClass.py", line 324, in get_repo
    headers, data = self.__requester.requestJsonAndCheck(
  File "/home/xxx/.local/lib/python3.8/site-packages/github/Requester.py", line 317, in requestJsonAndCheck
    return self.__check(
  File "/home/xxx/.local/lib/python3.8/site-packages/github/Requester.py", line 342, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/reference/repos#get-a-repository"}
```

This project is not stable.

**Comment by nicolai-wachenschwan** [comment]
Had the same Issue, you need to install the missing libs manual. I had to import 4 libs manual...
